FROM ubuntu:20.04 AS builder

RUN apt-get update && \
	apt-get install --no-install-suggests --no-install-recommends --yes\
	gcc git make ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
	bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
	gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
	libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
	mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils \
	rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev && \
	export GIT_SSL_NO_VERIFY=1 && \
	git config --global http.sslverify false
 
RUN wget --no-check-certificate "https://github.com/shenwei356/seqkit/releases/download/v2.2.0/seqkit_linux_amd64.tar.gz" -O /tmp/seqkit.tar.gz && \
	tar zxvf /tmp/seqkit.tar.gz -C /usr/bin/ && rm /tmp/seqkit.tar.gz

RUN git clone https://github.com/hyattpd/Prodigal.git && \
	cd Prodigal && \
	make install 

FROM alpine
MAINTAINER iskoldt-X

COPY --from=builder /usr/bin/seqkit /usr/bin/

RUN apk --no-cache add parallel

ENTRYPOINT ["parallel", "--will-cite"]
