package:
    name: plasmer
    version: "23.03.22"

build:
    number: 1
    binary_relocation: True
    always_include_files:
        - bin/assign_taxon_labels.R
        - bin/checkDB.sh
        - bin/check_length_by_input.py
        - bin/extract_predPlasmids_seqs.py
        - bin/getFeatBlastn.pl
        - bin/getFeatDomTbl.pl
        - bin/getFeatMDS.pl
        - bin/getFeatRiboRNA.pl
        - bin/mergeFeatsPredict.R
        - bin/Plasmer
        - bin/predict_by_rpmodel.R
source:
    git_url: https://github.com/nekokoe/Plasmer.git
    git_rev: main


requirements:
    build:
        - python ==3.10.4
    run:
        - python ==3.10.4
        - biopython
        - seqkit ==2.2.0
        - perl ==5.26.2
        - kmer-db ==1.9.4
        - Prodigal ==2.6.3
        - HMMER ==3.3.2
        - BLAST ==2.10.1
        - INFERNAL ==1.1.4
        - diamond ==2.0.15
        - Parallel
        - Kraken2 ==2.1.2
        - R ==4.2.0
        - r-randomforest ==4.7_1.1
        - r-hash

test:
    commands:
        - cd $PREFIX/bin && ls
        - Plasmer -h

about:
    home: https://github.com/nekokoe/Plasmer
    license: MIT
